app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :imports
  root 'imports#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'users/contacts', to: 'users#contacts'
  get 'imports/:id/logs', to: 'imports#logs', as: "logs"
  resources :users, except: [:new]
end

app/app/models/import.rb
# frozen_string_literal: true

class Import < ApplicationRecord
  require 'csv'
  require 'credit_card_validations/string'

  enum status_options: {
    on_hold: "on hold",
    processing: "processing",
    failed: "failed",
    finished: "finished",
  }, _prefix: :status
  
  attr_accessor :header

  belongs_to :user
  has_many :logs
  has_one_attached :file
  validates :status, presence: true,
            inclusion: {
              in: status_options.values,
              message: "%{value} is not a valid status"
            }
  validates_size_of :file, maximum: 3.megabytes,
                    message: "should be less than 3MB"
  validate :file_validation
  
  def franchise(cc)
    if (cc)
      CreditCardValidations.add_brand(:discover, {length: 16, prefixes: '6011'})
      return { franchise: cc.credit_card_brand_name }
    else
      return { franchise: nil }
    end
  end

  def encrypt(cc)
    if(cc)
      return ('*' * (cc.length - 4) + cc[-4, 4])
    else
      return nil
    end
  end

  def get_contact(row)
    attributes = {}
    header.each do |key, value|
      attributes[key.to_sym] = row[value]
    end
    hash = franchise(attributes[:credit_card])
    attributes[:credit_card] = encrypt(
      attributes[:credit_card]
                                      )
                                      attributes.merge(hash)
  end

  def has_valid_headers?(headers)
    header.values.each do |value|
      return false unless headers.include?(value)
    end
    true
  end          

  def file_validation
    errors.add(:file, 'no file added') unless file.attached?
    
    if file.attached? && !file.content_type.in?("text/csv")
      errors.add(:file, "must be a .csv extension.")
    end
  end

  def update_status!(status)
    self.status = status
    self.save
  end

  def save_log(message)
    register = Log.new(error: message, import: self)
    register.save
  end

  def run
    update_status!("processing")
    i = 0
    saved = 0
    temp = file.download
    invalid_header = false
    begin
      CSV.parse(temp, headers: true) do |row|
        if i == 0
          unless has_valid_headers?(row.headers)
            save_log("Wrong headers")
            invalid_header = true
            break
          end
        end
        i += 1;
        contact = Contact.new( get_contact(row) )
        contact.user = user
        if contact.valid?
          if user.contacts.find_by(email: contact.email)
            save_log(
              "Line #{i + 1} \
              - \nRow #{row.to_s} \
              - \nEmail error: Contact email already exist"
            )
            next
          end
        end
        if contact.save
          saved += 1
        else
          if contact.errors[:franchise].length > 0
            contact.franchise = "empty"
            contact.credit_card = "is invalid"
            contact.valid?
          end
          save_log(
            "Line #{i + 1} \
            - \nRow #{row.to_s} \
            -\n #{contact.errors.full_messages.join(', ')}"
          )
        end
      end
    rescue => exception
      puts exception
    end
    if invalid_header || (saved == 0 && i != 0)
      update_status!("failed")
    else
      update_status!("finished")
    end
  end

end

app/app/controllers/imports_controller.rb
# frozen_string_literal: true

class ImportsController < ApplicationController
  before_action :require_user, :set_import, only: %i[show]

  def index
    if logged?
      @imports = current_user.imports
    else
      redirect_to login_path
    end
  end

  def show
    unless current_user.imports.find_by(id: params[:id])
      flash[:alert] = "Current user can't access that route."
      redirect_to root_path
    end
  end

  def new
    @import = Import.new
  end

  def create
    @import = Import.new(import_params)
    @import.status = 'on hold'
    @import.user = current_user

    unless @import.header
      flash[:alert] = 'Header not found'
      redirect_to root_path
      return
    end

    respond_to do |_format|
      if @import.save
        ProcessCsvJob.perform_later({ id: @import.id, header: @import.header })
        flash[:notice] = 'Import was successfully saved.'
        redirect_to root_path
        return
      else
        flash[:alert] = 'Something went wrong, verify to upload the text file'
        redirect_to root_path
        return
      end
    end
  end

  def logs
    import = Import.find_by(id: params[:id])
    if !(import) || (import.user != current_user)
      render :file => "#{Rails.root}/public/404.html", layout: false, status: :not_found
      return
    end
    @logs = import.logs.paginate(page: params[:page], per_page: 10)
  end

  private

  def set_import
    @import = Import.find_by(id: params[:id])
  end

  def import_params
    params.require(:import).permit(:file,
                                   header: %i[
                                     name
                                     birthdate
                                     phone
                                     address
                                     credit_card
                                     email
                                   ])
  end
end

app/app/helpers/imports_helper.rb
# frozen_string_literal: true

module ImportsHelper
end

app/app/views/imports/_form.html.erb
<%= form_with(model: import) do |form| %>
  <% if import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
        <% import.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-3">
    <h2>Header</h2>
    <div class="field">
      <%= form.label 'header[name]', 'Name' %>
      <%= form.text_field 'header[name]', placeholder: "Enter corresponding header", required: true %>
    </div>
    <div class="field">
      <%= form.label 'header[birthdate]', 'Birthdate' %>
      <%= form.text_field 'header[birthdate]', placeholder: "Enter corresponding header", required: true %>
    </div>
    <div class="field">
      <%= form.label 'header[phone]', 'Phone' %>
      <%= form.text_field 'header[phone]', placeholder: "Enter corresponding header", required: true %>
    </div>
    <div class="field">
      <%= form.label 'header[address]', 'Address' %>
      <%= form.text_field 'header[address]', placeholder: "Enter corresponding header", required: true %>
    </div>
    <div class="field">
      <%= form.label 'header[address]', 'Credit card' %>
      <%= form.text_field 'header[credit_card]', placeholder: "Enter corresponding header", required: true %>
    </div>
    <div class="field">
      <%= form.label 'header[address]', 'Email' %>
      <%= form.text_field 'header[email]', placeholder: "Enter corresponding header", required: true %>
    </div>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/app/views/imports/index.html.erb
<h1>Home Page</h1>
<% if logged? %>
    <%= link_to "logout", {:controller=> "sessions", :action=> "destroy"}, :method => :delete%>
    <%= link_to "Contacts", users_contacts_path, class: "nav-link" %>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>

    <h1>Imports</h1>

    <table>
      <thead>
        <tr>
          <th>File</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
      <% @imports.each do |import| %>
        <tr>
          <td><%= import.file.filename.to_s %></td>
          <td><%= import.status %></td>
          <% if import.logs.empty? %>
            <td>No errors</td>
          <% else %>
            <td><%= link_to 'Failed registers', logs_path(import) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
    </table>

    <br>

    <%= link_to 'New Import', new_import_path %>
<% end %>

app/app/views/imports/logs.html.erb
<h1>Import Logs</h1>
<%= link_to 'Home', root_path %>
<div class="flickr_pagination">
  <%= will_paginate @logs, :container => false %>
</div>
<% if @logs.empty? %>
  <div><p>No Logs</p></div>
<% else %>
  <p>List of errors:</p>
    <% @logs.each do |register| %>
      <p><%= register.error %></p>
    <% end %>
<% end %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @logs, :container => false %>
</div>

app/app/views/imports/new.html.erb
<h1>New Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Back', imports_path %>

app/app/views/imports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File:</strong>
  <%= @import.file.filename %>
</p>

<%= link_to 'Download', @import.file, download: '' %>

<%= link_to 'Back', imports_path %>